instance:
  dashboardLabel: ""
  disableDefaultAdminSecret: false
  replicas: 1

  ingress:
    enabled: false
    className: ""
    host: example.com
    path: /
    pathType: Prefix
    port: 3000

  config:
    rootUrl: "https://example.com"
    database: {}
    authGoogle: {}
  env: []
folders: {}
datasources: {}
