{{- range $name, $policyConfig := .Values.alerting.notificationPolicies }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: {{ $name }}
  labels:
    {{- include "grafana-operator-crd.labels" $ | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: {{ $.Values.instance.dashboardLabel | default (include "grafana-operator-crd.fullname" $) | quote }}
  route:
    {{- tpl (toYaml $policyConfig.route) $ | nindent 4 }}
{{- end }}
