YAML
{{- range $key, $folder := .Values.folders }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  # Имя ресурса в Kubernetes
  name: {{ $key }}
  labels:
    {{- include "grafana-operator-crd.labels" $ | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      dashboards: {{ $.Values.instance.dashboardLabel | default (include "grafana-operator-crd.fullname" $) | quote }}
  
  title: {{ $folder.title | default $key | quote }}

  # Исправлено: parentFolderRef ожидает строку, а не объект!
  {{- if $folder.parentFolderRef }}
  parentFolderRef: {{ $folder.parentFolderRef | quote }}
  {{- end }}
{{- end }}
